# Shape of an Array

###### The shape of an array is the number of elements in each dimension

In [13]:
import numpy as np
arr = np.array([[1,2,3,4,6],[6, 7, 8, 9,7]])

# printing the shape of a 2-D array
print(arr)
print(arr.shape)


[[1 2 3 4 6]
 [6 7 8 9 7]]
(2, 5)


In [11]:
# creating an array with 5 dimension using ndmin using a vector with values 1,2,3,4 and varify that the last dimension has value 4
import numpy as np
arr_1 = np.array([1,2,3,4], ndmin = 5)

print(arr_1)
print(f"The shape of an array is {arr_1.shape}")

[[[[[1 2 3 4]]]]]
The shape of an array is (1, 1, 1, 1, 4)


### What does the shape tuple represent ?


###### Integers at every index tells abount the number of element the corresponding dimension has. 