# NumPy Joining Array

###### Joining means putting the content of two or more array in a single array. In numpy we join array by using axes. We pass a sequence of array that we want to join to the concatenate() function along with the axis, if not passed axis it is taken as 0

In [24]:
import numpy as np

arr1 = np.array([1,2,3,4])
arr2 = np.array([2,4,6,8])
arr3 = np.array([1,3,5,7])

combined_arr = np.concatenate((arr1, arr2, arr3))
print(f"The concatenated array so formed is: {combined_arr}")

The concatenated array so formed is: [1 2 3 4 2 4 6 8 1 3 5 7]


###### Joining two 2-D arrays along rows (axis=1):

In [7]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis = 1)

print(arr)



[[1 2 5 6]
 [3 4 7 8]]


#### Joining Arrays Using Stack Functions

###### Stacking is same as concatenation, the only difference is that stacking is done along a new axis.. We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking. We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [26]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis = 1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


#### Stacking Along Rows

###### NumPy provides a helper function - hstack() to stack along rows

In [30]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


#### Stacking Along Columns

###### NumPy provides a helper function: vstack()  to stack along columns.

In [22]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]
