# NumPy Array Copy vs View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5,6])

# using the copy method to copy the array arr
x = arr.copy()
arr[0] = 69

print(f"The original array is {arr}")
print(f"The copied array is {x}")

The original array is [69  2  3  4  5  6]
The copied array is [69  2  3  4  5  6]


###### Working with VIEW

In [4]:

# creating a new numpy array
arr = np.array([9, 89, 34, 2, 33])
x = arr.view()

arr[0] = 99

print(f"The orignal array {arr}")
print(f"The array after using view is {x}")

The orignal array [99 89 34  2 33]
The array after using view is [99 89 34  2 33]


###### Making Change in the view function
Any changes made to the view will affect the original array

In [5]:
x[0] = 3669
print(arr)
print(x)

[3669   89   34    2   33]
[3669   89   34    2   33]


### Check if Array Owns its Data
Copies owns the data and views doesn't owns the data

Every NumPy array has the attribute base that returns None if the array owns the data
Otherwise the base attribute refers to the original object

In [7]:

# creating a new array
arr = np.array([87, 34, 23])

# using copy() method
x_copy = arr.copy()
y_view = arr.view()

print(x_copy.base)
print(y_view.base)

None
[87 34 23]
