# Numpy Array Filter

###### Getting some elements out of an existing array and creating a new array out of them is called filtering.

In [4]:
import numpy as np

arr = np.array([69, 96, 36, 63])
x = [True, False, True, False]

new_arr = arr[x]
print(new_arr)

# the new array contains only the values where the filter array had the value True

[69 36]


### Creating the Filter Array

In [7]:
# Create a filter array that will return only values higher than 69:

arr = np.array([99, 68, 70, 8, 76, 20, 59])

# creating an empty list
filter_arr = []

for element in arr:
    if element > 69:
        filter_arr.append(True)
        
    else:
        filter_arr.append(False)
        
new_arr = arr[filter_arr]
print(filter_arr)
print(new_arr)

[True, False, True, False, True, False, False]
[99 70 76]


In [8]:
# Create a filter array that will return only even elements from the original array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


### Creating Filter Directly From Array

In [9]:
# Creating a filter array that will return only values higher than 69:
arr = np.array([99, 68, 70, 8, 76, 20, 59])

filter_arr = arr > 69
new_arr = arr[filter_arr]
print(filter_arr)
print(new_arr)


[ True False  True False  True False False]
[99 70 76]
